export type Funcionario = {
  id: string;
  nome: string;
  cpf: string;
  cnh: string;
  cnhVencimento?: string;
  cnhCategoria?: string;
  celular: string;
  email?: string;
  endereco: string;
  cep?: string;
  numero?: string;
  complemento?: string;
  cidade: string;
  funcao?: "motorista" | "ajudante" | "outro";
  toxicoUltimoExame?: string;
  toxicoVencimento?: string;
  status: "trabalhando" | "disponivel" | "folga" | "ferias";
  tipoContrato: "integral" | "temporario" | "folguista" | "inativo";
  unidadeNegocio: "frigorifico" | "ovos" | "ambos";
  dataAdmissao?: string;
  salario?: string | null;
  observacao?: string;
  ativo: boolean;
  dataCriacao?: any;
  dataAtualizacao?: any;
};

export type FuncionarioInput = {
  nome: string;
  cpf: string;
  cnh: string;
  cnhVencimento?: string;
  cnhCategoria?: string;
  celular: string;
  email?: string;
  endereco: string;
  cep?: string;
  numero?: string;
  complemento?: string;
  cidade: string;
  funcao?: "motorista" | "ajudante" | "outro";
  toxicoUltimoExame?: string;
  toxicoVencimento?: string;
  status: "trabalhando" | "disponivel" | "folga" | "ferias";
  tipoContrato: "integral" | "temporario" | "folguista" | "inativo";
  unidadeNegocio: "frigorifico" | "ovos" | "ambos";
  dataAdmissao?: string;
  salario?: string;
  observacao?: string;
  ativo: boolean;
};
export * from "../funcionarios/types";
